name:                Kroha
version:             1.2.1.0
github:              "vorotynsky/HLasm"
license:             GPL-3
author:              "Vorotynsky Maxim"
maintainer:          "vorotynsky.maxim@gmail.com"
copyright:           "2020 Vorotynsky Maxim"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vorotynsky/HLasm#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- parsec >= 3.1.0 && <= 3.1.14.0
- extra >= 1.0 && < 1.8
- comonad >= 5 && < 5.1
- hashmap >= 1.0.0 && < 1.4

executables:
  Kroha:
    source-dirs:      src
    main:             Main.hs

tests:
  Kroha-tests:
    source-dirs:      
    - test
    - src
    main:             Spec.hs
    dependencies:
    - HUnit == 1.6.*
    - Diff >= 0.2 && < 0.5
